#!/usr/bin/env dart
// Generates SQL seed from assets/comments/ with protocol id remap (+1).
//
// Usage:
//   dart run tool/generate_supabase_seed.dart
//   dart run tool/generate_supabase_seed.dart \
//     --input assets/comments --output supabase/seeds/demo_messages.sql

import 'dart:convert';
import 'dart:io';

const _demoChatId = 1;
const _demoUserId = 1;
const _batchSize = 100;

void main(List<String> args) {
  final inputDir = _arg(args, '--input') ?? 'assets/comments';
  final outputPath =
      _arg(args, '--output') ?? 'supabase/seeds/demo_messages.sql';

  final manifestFile = File('$inputDir/manifest.json');
  if (!manifestFile.existsSync()) {
    stderr.writeln('Missing manifest: ${manifestFile.path}');
    exit(1);
  }

  final manifest =
      jsonDecode(manifestFile.readAsStringSync()) as Map<String, dynamic>;
  final chunks = (manifest['chunks'] as List<Object?>).cast<String>();

  final buffer = StringBuffer()
    ..writeln('-- Generated by tool/generate_supabase_seed.dart')
    ..writeln('-- Legacy id N -> protocol id N + 1')
    ..writeln();

  var total = 0;
  for (final chunkName in chunks) {
    final chunkPath = '$inputDir/$chunkName';
    final list = jsonDecode(File(chunkPath).readAsStringSync()) as List<Object?>;
    final rows = <String>[];

    for (final raw in list) {
      final m = raw as Map<String, dynamic>;
      final legacyId = m['id']! as int;
      final protocolId = legacyId + 1;
      final sender = m['sender']! as String;
      final content = m['content']! as String;
      final createdAt = m['createdAt']! as String;
      final extra = jsonEncode({'legacy_sender': sender});
      rows.add(
        '($_demoChatId, $protocolId, $_demoUserId, '
        '${_sqlQuote(createdAt)}::timestamptz, '
        '${_sqlQuote(createdAt)}::timestamptz, '
        "0, 0, NULL, ${_sqlQuote(content)}, NULL, ${_sqlQuote(extra)}::jsonb)",
      );
      total++;
    }

    for (var i = 0; i < rows.length; i += _batchSize) {
      final end = (i + _batchSize < rows.length) ? i + _batchSize : rows.length;
      buffer
        ..writeln(
          'INSERT INTO public.messages '
          '(chat_id, id, sender_id, created_at, updated_at, kind, flags, '
          'reply_to_id, content, rich_content, extra) VALUES',
        )
        ..writeln(rows.sublist(i, end).join(',\n'))
        ..writeln('ON CONFLICT (chat_id, id) DO NOTHING;')
        ..writeln();
    }
  }

  final out = File(outputPath);
  out.parent.createSync(recursive: true);
  out.writeAsStringSync(buffer.toString());
  stdout.writeln('Wrote $total messages to $outputPath');
}

String? _arg(List<String> args, String name) {
  final i = args.indexOf(name);
  if (i < 0 || i + 1 >= args.length) return null;
  return args[i + 1];
}

String _sqlQuote(String value) {
  return "'${value.replaceAll("'", "''")}'";
}
